from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
APP_VUE = ROOT / "frontend" / "src" / "App.vue"
API_TS = ROOT / "frontend" / "src" / "api.ts"
STYLE_CSS = ROOT / "frontend" / "src" / "style.css"


class FrontendAIProfileTaskTests(unittest.TestCase):
    def test_task_console_exposes_ai_profile_task(self):
        source = APP_VUE.read_text(encoding="utf-8")
        api_source = API_TS.read_text(encoding="utf-8")

        self.assertIn('"ai_profile"', source)
        self.assertIn("AI画像", source)
        self.assertIn("aiProfileTask.profile_package_ids_text", source)
        self.assertIn("profileSourceGroups", source)
        self.assertIn("fetchProfileSourceGroups", api_source)
        self.assertIn("profile_source_group_id", source)
        self.assertIn("isAIProfileSourceGroupDisabled", source)
        self.assertIn("isAIProfilePackageIdsDisabled", source)
        self.assertIn(':disabled="isAIProfileSourceGroupDisabled"', source)
        self.assertIn(':disabled="isAIProfilePackageIdsDisabled"', source)
        self.assertNotIn("aiProfileTask.input_mode", source)
        self.assertNotIn("画像输入方式", source)
        self.assertIn('model_provider: "deepseek"', source)
        self.assertIn('api_base_url: "https://api.deepseek.com"', source)
        self.assertIn('model_name: "deepseek-v4-pro"', source)
        self.assertIn("aiProfileTask.api_key", source)
        self.assertIn("aiProfileTask.temperature", source)
        self.assertIn("aiProfileTask.timeout_seconds", source)
        self.assertNotIn("aiProfileTask.prompt_version", source)
        self.assertNotIn('value="claude_code"', source)
        self.assertIn("startAIProfileTask", api_source)
        self.assertIn('"/tasks/ai-profile"', api_source)

    def test_ai_profile_review_uses_directory_modal_layout(self):
        source = APP_VUE.read_text(encoding="utf-8")
        styles = STYLE_CSS.read_text(encoding="utf-8")

        self.assertIn("selectedAIProfileResultId", source)
        self.assertIn("openAIProfilePreview", source)
        self.assertIn("closeAIProfilePreview", source)
        self.assertIn("previewAIProfileResult", source)
        self.assertIn("companyNameForAIProfile", source)
        self.assertIn("regionForAIProfile", source)
        self.assertIn("ai-profile-directory-board", source)
        self.assertIn("ai-profile-directory", source)
        self.assertIn("previewAIProfileResult.company_name", source)
        self.assertIn("previewAIProfileResult.country", source)
        self.assertIn("ai-profile-preview-backdrop", source)
        self.assertIn("ai-profile-preview-modal", source)
        self.assertIn('aria-label="关闭画像预览"', source)
        self.assertIn("aiProfileDirectoryPageSizeOptions", source)
        self.assertIn("setAIProfileDirectoryPageSize", source)
        self.assertIn("每页目录", source)
        self.assertIn('limit: 100', source)
        self.assertIn("[100, 300, 500]", source)
        self.assertIn('aria-label="上一页目录"', source)
        self.assertIn('aria-label="下一页目录"', source)
        self.assertNotIn("上一份画像", source)
        self.assertNotIn("下一份画像", source)
        self.assertIn("ai-profile-directory-list", source)
        self.assertIn("height: clamp(560px, calc(100vh - 230px), 820px)", styles)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", styles)
        self.assertIn("position: fixed", styles)
        self.assertIn("inset: 0", styles)

    def test_ai_profile_directory_supports_selection_and_export(self):
        source = APP_VUE.read_text(encoding="utf-8")

        self.assertIn("selectedAIProfileRows", source)
        self.assertIn("aiProfileFilteredSelectionActive", source)
        self.assertIn("selectAllFilteredAIProfiles", source)
        self.assertIn("toggleAIProfileSelection", source)
        self.assertIn("exportSelectedAIProfiles", source)
        self.assertIn("promptForAIProfileExportFilename", source)
        self.assertIn("defaultAIProfileExportFilename", source)
        self.assertIn("normalizeHtmlFilename", source)
        self.assertIn("请输入导出文件名", source)
        self.assertIn("downloadHtmlFile", source)
        self.assertIn("导出HTML报告", source)
        self.assertIn("全选", source)
        self.assertIn("已选", source)
        self.assertNotIn("筛选后全选", source)

    def test_ai_profile_export_builds_offline_html_report(self):
        source = APP_VUE.read_text(encoding="utf-8")

        self.assertIn("buildAIProfileExportHtml", source)
        self.assertIn("renderAIProfileExportDirectory", source)
        self.assertIn("renderAIProfileReportPage", source)
        self.assertIn("renderAIProfileReportSection", source)
        self.assertIn("escapeHtml", source)
        self.assertIn("downloadHtmlFile", source)
        self.assertIn("const filename = promptForAIProfileExportFilename(exportedAt)", source)
        self.assertIn("if (!filename) return", source)
        self.assertIn("filename.endsWith(\".html\") ? filename : `${filename}.html`", source)
        self.assertIn("text/html;charset=utf-8", source)
        self.assertIn(".html", source)
        self.assertIn("<!doctype html>", source)
        self.assertIn("AI画像离线报告", source)
        self.assertIn("report-shell", source)
        self.assertIn("profile-report", source)
        self.assertIn("score-breakdown", source)
        self.assertIn("report_sections", source)
        self.assertIn("mode_label", source)
        self.assertIn('label: "客户画像摘要"', source)
        self.assertIn('label: "产品匹配度"', source)
        self.assertIn('label: "评分明细"', source)
        self.assertIn('label: "推荐动作"', source)
        self.assertIn('label: "证据"', source)
        self.assertIn('label: "风险点"', source)
        self.assertIn('label: "对应联系方式"', source)
        self.assertIn("result.contacts || []", source)
        self.assertIn("renderAIProfileContactList", source)
        self.assertNotIn("contact.source", source)
        self.assertNotIn("未知来源", source)
        self.assertNotIn("downloadJsonFile", source)
        self.assertNotIn("buildAIProfileExportPackage", source)
        self.assertNotIn('schema_version: "ai-profile-export.v1"', source)
        self.assertNotIn("raw_record", source)

    def test_ai_profile_preview_uses_report_layout(self):
        source = APP_VUE.read_text(encoding="utf-8")
        styles = STYLE_CSS.read_text(encoding="utf-8")

        self.assertIn("ai-profile-report", source)
        self.assertIn("ai-profile-section-body", source)
        self.assertIn("profile-summary", source)
        self.assertIn("profile-product-fit", source)
        self.assertIn("profile-score", source)
        self.assertIn("profile-evidence", source)
        self.assertIn("profile-risks", source)
        self.assertIn("profile-recommendation", source)
        self.assertIn("profile-contacts", source)
        self.assertIn("previewAIProfileResult.contacts", source)
        self.assertIn("formatAIProfileContactKind", source)
        self.assertIn("grid-template-rows: auto auto auto auto", styles)
        self.assertIn("overflow: auto", styles)
        self.assertIn(".ai-profile-report", styles)
        self.assertIn("height: min(920px, calc(100vh - 48px))", styles)
        self.assertIn("overscroll-behavior: contain", styles)
        self.assertIn("grid-template-columns: minmax(128px, 180px) minmax(0, 1fr)", styles)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", styles)
        self.assertIn(".ai-profile-section-body", styles)
        self.assertIn("overflow: visible", styles)
        self.assertIn(".ai-profile-preview-body .ai-profile-page", styles)
        self.assertIn("height: auto", styles)
        self.assertIn("min-height: 100%", styles)
        self.assertNotIn("previewAIProfileRawJson", source)
        self.assertNotIn("查看原始 JSON", source)
        self.assertNotIn("raw-json-detail", source)
        self.assertNotIn(".raw-json-detail", styles)
        self.assertNotIn("ai-profile-sections-grid", source)
        self.assertNotIn(".ai-profile-sections-grid", styles)
        self.assertNotIn("grid-template-columns: repeat(auto-fit, minmax(320px, 1fr))", styles)
        self.assertNotIn("grid-auto-rows: minmax(180px, auto)", styles)
        self.assertNotIn("min-height: 180px", styles)
        self.assertNotIn("min-height: 170px", styles)
        self.assertNotIn(".profile-score .ai-profile-section-body", styles)
        self.assertNotIn(".profile-evidence .ai-profile-section-body", styles)
        self.assertNotIn(".profile-risks .ai-profile-section-body", styles)
        self.assertNotIn(".profile-summary,\n.profile-product-fit,\n.profile-recommendation", styles)


if __name__ == "__main__":
    unittest.main()
